name: gotest

on:
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: mod verify
        run: go mod verify

      - name: Run Tests
        run: make test